### ISSUE TITLE
Hi not sure if you still maintain this but-

### ISSUE THREAD

**Issue by iop3** [VulcanWM/munity#19]
```Traceback (most recent call last):
  File "C:\Users\(REDACTED)\(REDACTED)\munity\main.py", line 1, in <module>
    from app import app
  File "C:\Users\(REDACTED)\(REDACTED)\munity\app.py", line 2, in <module>
    from functions import getrandomline, addcookie, delcookies, getcookie, makeaccount, gethashpass, getuser, addmoney, addxp, changesonglyricscore, xpleaderboard, moneyleaderboard, changealbumcoverscore, getrandomalbumcover, getalbumnames, coverimagetobyte, getalbumcover, searchartist, removebrackets
  File "C:\Users\(REDACTED)\(REDACTED)\munity\functions.py", line 22, in <module>
    client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
  File "C:\Users\(REDACTED)\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spotipy\oauth2.py", line 201, in __init__
    self.client_id = client_id
  File "C:\Users\(REDACTED)\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spotipy\oauth2.py", line 94, in client_id
    self._client_id = _ensure_value(val, "client_id")
  File "C:\Users\(REDACTED)\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spotipy\oauth2.py", line 70, in _ensure_value
    raise SpotifyOauthError(msg)
```
um, bug?

**Comment by VulcanWM** [comment]
thanks for making me aware! I’ll try to fix it soon

**Comment by iop3** [comment]
np
